- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart containerd
  ansible.builtin.systemd:
    state: restarted
    name: containerd

- name: Restart docker
  ansible.builtin.systemd:
    state: restarted
    name: docker

- name: Restart kubelet
  ansible.builtin.systemd:
    state: restarted
    name: kubelet
